SELECT p.* FROM PAYMENT p JOIN PAYMENTTYPE t ON p.TYPE_ID = t.ID  WHERE t.NAME = 'MONTHLY';
SELECT m.* FROM MARK m JOIN SUBJECT s ON m.SUBJECT_ID = s.ID  WHERE s.NAME = 'Art';
SELECT s.* FROM STUDENT s JOIN PAYMENT p ON s.ID = p.STUDENT_ID WHERE p.TYPE_id = SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY';
SELECT s.* FROM STUDENT s LEFT JOIN MARK m ON s.ID = m.STUDENT_ID WHERE m.SUBJECT_ID = SELECT ID FROM SUBJECT WHERE NAME = 'Math';

