SELECT*FROM PAYMENT WHERE TYPE_ID = SELECT ID FROM PAYMENTTYPE WHERE name = 'MONTHLY';
SELECT*FROM MARK WHERE SUBJECT_ID = SELECT ID FROM SUBJECT WHERE NAME = 'Art';
SELECT s.* FROM STUDENT s LEFT JOIN PAYMENT p ON s.ID = p.STUDENT_ID WHERE p.TYPE_id = SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY';
SELECT s.* FROM STUDENT s LEFT JOIN MARK m ON s.ID = m.STUDENT_ID WHERE m.SUBJECT_ID = SELECT ID FROM SUBJECT WHERE NAME = 'Math';