DELETE s.*, m.*, p.* FROM STUDENT s JOIN MARK m ON s.ID = m.STUDENT_ID JOIN PAYMENT p ON m.STUDENT_ID = p.STUDENT_ID WHERE m.MARK > 4;
DELETE s.* FROM STUDENT s JOIN MARK m ON s.ID = m.STUDENT_ID WHERE m.MARK < 4;
DELETE t.*, p.* FROM PAYMENTTYPE t JOIN PAYMENT p ON t.ID = p.TYPE_ID WHERE t.NAME = 'DAILY';
DELETE FROM MARK WHERE MARK <= 7;