SELECT * FROM MARK DESC WHERE MARK > 6;
SELECT * FROM PAYMENT DESC WHERE AMOUNT > 300;
SELECT * FROM PAYMENTTYPE ORDER BY NAME ASC;
SELECT * FROM STUDENT ORDER BY NAME DESC;
SELECT s.ID, s.NAME, s.BIRTHDAY, s.GROUPNUMBER FROM STUDENT s LEFT JOIN PAYMENT p ON s.ID = p.STUDENT_ID WHERE p.AMOUNT  = 500 ORDER BY s.NAME;
