SELECT*FROM PAYMENT WHERE AMOUNT >= 500;
SELECT*FROM STUDENT WHERE BIRTHDAY > DATEADD(YEAR, -20, CURRENT_DATE);
SELECT*FROM STUDENT WHERE GROUPNUMBER = 10 AND BIRTHDAY < SELECT DATEADD( YEAR, -20, SELECT CURDATE() today);
SELECT*FROM STUDENT WHERE NAME LIKE 'Mike%' OR GROUPNUMBER >= 4 AND GROUPNUMBER <= 6;
SELECT*FROM PAYMENT WHERE PAYMENT_DATE > DATEADD(MONTH, -8, CURRENT_DATE);
SELECT*FROM STUDENT WHERE NAME LIKE 'A%';
SELECT*FROM STUDENT WHERE (NAME LIKE 'Roxy%' AND GROUPNUMBER = 4) OR (NAME LIKE 'Tallie%' AND GROUPNUMBER = 9);