INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (1, 'John', '2000-01-15', 1);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (2, 'Chris', '2001-01-15', 1);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (3, 'Carl', '2000-06-04', 1);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (4, 'Oliver', '2000-03-07', 2);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (5, 'James', '2000-07-18', 2);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (6, 'Lucas', '2000-12-21', 2);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (7, 'Henry', '2001-04-24', 2);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (8, 'Jacob', '2000-05-04', 3);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (9, 'Logan', '2000-09-12', 3);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (10, 'Max', '2000-10-11', 4);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (11, 'Mark', '2001-05-03', 5);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (12, 'Luca', '2001-02-14', 4);
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, GROUPNUMBER) VALUES (13, 'George', '2001-02-03', 5);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (1, 'Art', 'Unleash your creativity in our art lesson! Explore diverse techniques, mediums, and styles. Get expert guidance in painting, sketching, and sculpting. Join us for a transformative artistic experience!', 1);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (2, 'music ', 'Embark on a melodic journey with our music lessons! Learn various instruments, music theory, and composition. Develop your skills through practical exercises and personalized guidance. Join our passionate community and discover the joy of making music!', 1);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (3, 'Geography', 'Embark on a captivating journey through the world with our geography lessons! Explore diverse landscapes, cultures, and natural wonders. Dive deep into maps, climates, and global issues. Join us to broaden your knowledge and become a global citizen!', 2);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (4, 'History', 'Dive into history''s secrets. Explore civilizations, events, and influential figures. Gain insights into our past and present. Join us to unravel the past''s mysteriesSUBJECT !', 2);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (5, 'PE', 'Get active and have fun in our PE lessons! Engage in various sports, fitness activities, and team games. Improve your coordination, endurance, and teamwork skills. Join us for an energetic and enjoyable physical education experience!', 3);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (6, 'Math', 'Excel in math with our dynamic lessons! Explore concepts, solve problems, and boost analytical thinking. Join us to unlock the power of mathematics!', 3);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (7, 'Science', 'Discover captivating science! Dive into topics, experiment, and unlock natural wonders. Explore biology, chemistry, physics. Join us for an exciting scientific journey!', 4);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (8, 'IT', 'Explore IT wonders with us! Learn programming, web dev, cybersecurity. Gain hands-on experience, enhance skills. Join us to unlock tech''s potential!', 4);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (9, 'Literature', 'Explore literature''s depths! Analyze stories, themes, and engage in enriching discussions. Expand your literary horizons with us!', 5);
INSERT INTO SUBJECT(ID, NAME, DESCRIPTION, GRADE) VALUES (10, 'Political Science', 'Unveil political complexities! Analyze systems, policies, and power. Engage in enlightening discussions. Join us for political insights!', 5);
INSERT INTO PAYMENTTYPE(ID, NAME) VALUES (1, 'DAILY');
INSERT INTO PAYMENTTYPE(ID, NAME) VALUES (2, 'WEEKLY');
INSERT INTO PAYMENTTYPE(ID, NAME) VALUES (3, 'MONTHLY');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (1, SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY', 150.25, SELECT ID FROM STUDENT WHERE name = 'John', '2023-06-12');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (2, SELECT ID FROM PAYMENTTYPE WHERE name = 'MONTHLY', 500.00, SELECT ID FROM STUDENT WHERE name = 'Oliver', '2023-06-13');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (3, SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY', 150.25, SELECT ID FROM STUDENT WHERE name = 'Henry', '2023-06-14');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (4, SELECT ID FROM PAYMENTTYPE WHERE name = 'DAILY', 35.50, SELECT ID FROM STUDENT WHERE name = 'James', '2023-06-09');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (5, SELECT ID FROM PAYMENTTYPE WHERE name = 'MONTHLY', 500.00,SELECT ID FROM STUDENT WHERE name = 'Max', '2023-06-13');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (6, SELECT ID FROM PAYMENTTYPE WHERE name = 'DAILY', 35.50,SELECT ID FROM STUDENT WHERE name = 'Mark', '2023-06-14');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (7, SELECT ID FROM PAYMENTTYPE WHERE name = 'DAILY', 35.50,SELECT ID FROM STUDENT WHERE name = 'Chris', '2023-06-14');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (8, SELECT ID FROM PAYMENTTYPE WHERE name = 'MONTHLY', 500.00,SELECT ID FROM STUDENT WHERE name = 'Carl', '2023-06-13');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (9, SELECT ID FROM PAYMENTTYPE WHERE name = 'MONTHLY', 500.00,SELECT ID FROM STUDENT WHERE name = 'Oliver', '2023-06-13');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (10, SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY', 150.25, SELECT ID FROM STUDENT WHERE name = 'Lucas', '2023-06-14');
INSERT INTO PAYMENT(ID, TYPE_ID, AMOUNT, STUDENT_ID, PAYMENT_DATE) VALUES (11, SELECT ID FROM PAYMENTTYPE WHERE name = 'WEEKLY', 150.25, SELECT ID FROM STUDENT WHERE name = 'Jacob', '2023-06-14');
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (1, SELECT ID FROM STUDENT WHERE name = 'Chris', SELECT ID FROM SUBJECT WHERE name = 'Art', 8);
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (2, SELECT ID FROM STUDENT WHERE name = 'Oliver', SELECT ID FROM SUBJECT WHERE name = 'History', 5);
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (3, SELECT ID FROM STUDENT WHERE name = 'James', SELECT ID FROM SUBJECT WHERE name = 'Geography', 9);INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (4, SELECT ID FROM STUDENT WHERE name = 'Jacob', SELECT ID FROM SUBJECT WHERE name = 'Math', 4);
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (5, SELECT ID FROM STUDENT WHERE name = 'Logan', SELECT ID FROM SUBJECT WHERE name = 'PE', 9);
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (6, SELECT ID FROM STUDENT WHERE name = 'Max', SELECT ID FROM SUBJECT WHERE name = 'IT', 10);
INSERT INTO Mark(ID, STUDENT_ID, SUBJECT_ID, MARK) VALUES (7, SELECT ID FROM STUDENT WHERE name = 'Mark', SELECT ID FROM SUBJECT WHERE name = 'Political Science', 6);