ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY DATE NOT NULL;
ALTER TABLE MARK ADD CHECK (MARK > 0 AND MARK< 11);
ALTER TABLE MARK ALTER COLUMN STUDENT_ID BIGINT NOT NULL;
ALTER TABLE MARK ALTER COLUMN SUBJECT_ID BIGINT NOT NULL;
ALTER TABLE SUBJECT ADD CHECK (GRADE > 0 AND GRADE < 6);
ALTER TABLE PAYMENTTYPE add UNIQUE(NAME);
ALTER TABLE PAYMENT ALTER COLUMN TYPE_ID BIGINT NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN AMOUNT DECIMAL NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN PAYMENT_DATE DATETIME NOT NULL;