SELECT MIN (BIRTHDAY) AS SmallestStudent FROM STUDENT;
SELECT MIN (PAYMENT_DATE ) AS EarlyPayment FROM PAYMENT;
SELECT AVG(m.MARK) FROM MARK m JOIN SUBJECT s ON m.SUBJECT_ID = s.ID WHERE s.ID = SELECT ID FROM SUBJECT WHERE NAME = 'Math';
SELECT MIN(p.AMOUNT ) FROM PAYMENT p JOIN PAYMENTTYPE t ON p.TYPE_ID = t.ID WHERE t.ID = SELECT ID FROM PAYMENTTYPE WHERE NAME = 'WEEKLY';