CREATE TABLE Student (id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL, birthday DATE NOT NULL, groupNumber INT NOT NULL);
CREATE TABLE Subject (id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL, description  VARCHAR(255) NOT NULL, grade INT NOT NULL);
CREATE TABLE PaymentType (id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE Payment (id BIGINT NOT NULL PRIMARY KEY, type_id BIGINT NOT NULL, FOREIGN KEY (type_id) REFERENCES PaymentType(id), amount DECIMAL NOT NULL, student_id BIGINT  NOT NULL, FOREIGN KEY (student_id) REFERENCES Student(id), payment_date DATETIME NOT NULL);
CREATE TABLE Mark (id BIGINT NOT NULL PRIMARY KEY, student_id BIGINT NOT NULL, FOREIGN KEY (student_id) REFERENCES Student(id), subject_id  BIGINT NOT NULL, FOREIGN KEY (subject_id) REFERENCES Subject(id), mark INT NOT NULL);

