SELECT s.* FROM STUDENT s JOIN MARK m ON s.ID = m.STUDENT_ID  GROUP BY STUDENT_ID HAVING AVG(MARK) > 8;
SELECT s.ID, s.NAME FROM STUDENT s JOIN MARK m ON s.ID = m.STUDENT_ID  GROUP BY STUDENT_ID HAVING AVG(MARK) > 7;
SELECT s.ID, s.NAME FROM STUDENT s JOIN PAYMENT p ON s.ID = p.STUDENT_ID WHERE YEAR (PAYMENT_DATE ) = 2019 GROUP BY (STUDENT_ID) HAVING COUNT(*) > 2;