UPDATE SUBJECT SET grade = 5 WHERE name = 'End of Suburbia: Oil Depletion and the Collapse of the American Dream';
UPDATE STUDENT SET GROUPNUMBER = 8 WHERE NAME = 'Tremaine Worvill';
UPDATE PAYMENT SET AMOUNT = 500, STUDENT_ID = 2 WHERE PAYMENT_DATE > '2021-01-01' and TYPE_ID = 2;
UPDATE MARK SET MARK = 2 WHERE SUBJECT_ID  = 315;